import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateEnumType1773910360296 implements MigrationInterface {
    name = 'UpdateEnumType1773910360296'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."class_members_role_enum" AS ENUM('user', 'uniadmin', 'roomadmin', 'student', 'lecturer')`);
        await queryRunner.query(`CREATE TABLE "class_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "role" "public"."class_members_role_enum" NOT NULL DEFAULT 'student', "is_committee_member" boolean NOT NULL DEFAULT false, "can_create_notifications" boolean NOT NULL DEFAULT false, "can_create_forms" boolean NOT NULL DEFAULT false, "can_create_score_forms" boolean NOT NULL DEFAULT false, "joined_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "class" uuid, "user_id" uuid, CONSTRAINT "CHK_ec10dbcedee355426237c12b4f" CHECK ("role" IN ('roomadmin', 'student', 'lecturer')), CONSTRAINT "PK_c06d2c3bc732509dcbbab8d5730" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c38b69071bb1cad72777d45502" ON "class_members" ("class", "user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."checkbox_fields_input_type_enum" AS ENUM('string', 'number', 'file', 'checkbox')`);
        await queryRunner.query(`CREATE TABLE "checkbox_fields" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "index" integer NOT NULL, "label" character varying NOT NULL, "description" character varying, "input_type" "public"."checkbox_fields_input_type_enum" NOT NULL DEFAULT 'checkbox', "choice_count" integer NOT NULL, "is_required" boolean NOT NULL DEFAULT false, "is_multiple" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "update_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "form" uuid, CONSTRAINT "PK_d5699c122fde6c00a2dc102889e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6b4236fbc851d1dfadc6060279" ON "checkbox_fields" ("form") `);
        await queryRunner.query(`CREATE TABLE "checkbox_field_choices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "index" integer NOT NULL, "body" character varying NOT NULL, "submission_checkbox" uuid, CONSTRAINT "REL_739f9f6f4d288f71eb7f0e088e" UNIQUE ("submission_checkbox"), CONSTRAINT "PK_69534eae5b5aaba2b70902948f8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_739f9f6f4d288f71eb7f0e088e" ON "checkbox_field_choices" ("submission_checkbox") `);
        await queryRunner.query(`CREATE TABLE "submission_checkboxes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "checkbox_field_id" uuid, "submission" uuid, CONSTRAINT "REL_2d43b289afe25e6542ffe01b75" UNIQUE ("checkbox_field_id"), CONSTRAINT "PK_2600970eab4f2d485873ad89a77" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_03c60815fd5dcdc496e2a2c911" ON "submission_checkboxes" ("checkbox_field_id", "submission") `);
        await queryRunner.query(`CREATE TABLE "submissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "form_id" uuid, "user" uuid, CONSTRAINT "PK_10b3be95b8b2fb1e482e07d706b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4bebcd2af113fc32d00ed64d7e" ON "submissions" ("user", "form_id") `);
        await queryRunner.query(`CREATE TABLE "submission_answers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "body" character varying NOT NULL, "field" uuid, "submission" uuid, CONSTRAINT "REL_e353995ac74b8afd81d44ea89e" UNIQUE ("field"), CONSTRAINT "PK_32d8f1ef26cf32a2e8ba2f1fc13" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0c7afc9bb5f426d5020c7dea1c" ON "submission_answers" ("field", "submission") `);
        await queryRunner.query(`CREATE TYPE "public"."fields_label_enum" AS ENUM('null', 'outline_file', 'report_file', 'final_thesis')`);
        await queryRunner.query(`CREATE TYPE "public"."fields_input_type_enum" AS ENUM('string', 'number', 'file', 'checkbox')`);
        await queryRunner.query(`CREATE TYPE "public"."fields_unit_enum" AS ENUM('file', 'unit', 'character')`);
        await queryRunner.query(`CREATE TABLE "fields" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "index" integer NOT NULL, "label" "public"."fields_label_enum" NOT NULL, "title" character varying NOT NULL, "description" character varying, "input_type" "public"."fields_input_type_enum" NOT NULL DEFAULT 'string', "is_required" boolean NOT NULL DEFAULT false, "unit" "public"."fields_unit_enum" NOT NULL, "max_attempts" integer NOT NULL DEFAULT '20', "min_attempts" integer NOT NULL DEFAULT '1', "update_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "form" uuid, CONSTRAINT "PK_ee7a215c6cd77a59e2cb3b59d41" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f5f2c68138a8dabd583066aa8d" ON "fields" ("form") `);
        await queryRunner.query(`CREATE TABLE "forms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "is_join_form" boolean NOT NULL DEFAULT false, "label" character varying NOT NULL, "description" character varying, "field_count" integer NOT NULL, "is_auto_open" boolean NOT NULL DEFAULT false, "is_auto_close" boolean NOT NULL DEFAULT false, "email_notification_enabled" boolean NOT NULL DEFAULT true, "is_deleted" boolean NOT NULL DEFAULT false, "is_stopped" boolean NOT NULL DEFAULT false, "open_at" TIMESTAMP WITH TIME ZONE NOT NULL, "close_at" TIMESTAMP WITH TIME ZONE NOT NULL, "update_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "milestone" uuid, "created_by" uuid, CONSTRAINT "PK_ba062fd30b06814a60756f233da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a3b3a7866f18e227340c0e1c01" ON "forms" ("label", "milestone", "created_by", "is_auto_open", "is_auto_close", "is_deleted", "is_stopped") `);
        await queryRunner.query(`CREATE TABLE "score_form_rows" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "index" integer NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "student" uuid, "score_form" uuid, CONSTRAINT "PK_167e7f35eb59b73f48212913075" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5c3751f1bcb296748570b38595" ON "score_form_rows" ("student", "score_form") `);
        await queryRunner.query(`CREATE TABLE "score_form_cells" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "value" character varying NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" uuid, "row" uuid, "column" uuid, CONSTRAINT "PK_a6c354a8b56e4ccb40a75a46ae6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b4b4e45572d49b4656ee2cbff0" ON "score_form_cells" ("updated_by", "row", "column") `);
        await queryRunner.query(`CREATE TABLE "score_form_columns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "label" character varying NOT NULL, "score_form" uuid, CONSTRAINT "PK_6c3b5eee0dafb23568868cffee1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f9ff4add6e75b532cefe9a6920" ON "score_form_columns" ("score_form") `);
        await queryRunner.query(`CREATE TYPE "public"."score_forms_score_form_type_enum" AS ENUM('supervisor_score', 'reviewer_score', 'committee_score', 'attendance_check', 'bonus_score', 'others')`);
        await queryRunner.query(`CREATE TABLE "score_forms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "score_form_type" "public"."score_forms_score_form_type_enum" NOT NULL DEFAULT 'others', "label" character varying NOT NULL, "description" character varying, "field_count" integer NOT NULL, "is_auto_open" boolean NOT NULL DEFAULT false, "is_auto_close" boolean NOT NULL DEFAULT false, "email_notification_enabled" boolean NOT NULL DEFAULT true, "is_deleted" boolean NOT NULL DEFAULT false, "is_stopped" boolean NOT NULL DEFAULT false, "open_at" TIMESTAMP WITH TIME ZONE NOT NULL, "close_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "update_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, "milestone" uuid, CONSTRAINT "PK_886b88e54e4de99da664c91bed2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bec6aec16056db33a4fefa4bac" ON "score_forms" ("label", "milestone", "created_by", "is_auto_open", "is_auto_close", "is_deleted", "is_stopped") `);
        await queryRunner.query(`CREATE TABLE "milestones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "index" integer NOT NULL, "label" character varying DEFAULT true, "description" character varying DEFAULT true, "is_deleted" boolean NOT NULL DEFAULT false, "is_stopped" boolean NOT NULL DEFAULT false, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_by" uuid, "progress" uuid, CONSTRAINT "PK_0bdbfe399c777a6a8520ff902d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3981c3d8ecb4c98fd1feff697f" ON "milestones" ("progress", "label", "created_by", "is_deleted", "is_stopped") `);
        await queryRunner.query(`CREATE TABLE "progresses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "label" character varying DEFAULT true, "description" character varying DEFAULT true, "is_deleted" boolean NOT NULL DEFAULT false, "required_approval" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, "class" uuid, CONSTRAINT "REL_b6ff555471c0d266d5621b94ed" UNIQUE ("class"), CONSTRAINT "PK_8bd707ae89e9482ebf23658011e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "body" character varying NOT NULL, "email_notification_enabled" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "class" uuid, "created_by" uuid, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b85731582ba550f9f38cb193a4" ON "notifications" ("class", "created_by") `);
        await queryRunner.query(`CREATE TABLE "classes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "join_code" character varying, "label" character varying NOT NULL DEFAULT 'Lớp học mới', "description" character varying, "subject" character varying NOT NULL, "created_approval" boolean NOT NULL DEFAULT false, "required_approval" boolean NOT NULL DEFAULT false, "required_join_form" boolean NOT NULL DEFAULT false, "is_deleted" boolean NOT NULL DEFAULT false, "is_banned" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, CONSTRAINT "PK_e207aa15404e9b2ce35910f9f7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "supabase_id" character varying NOT NULL, "full_name" character varying NOT NULL, "email" character varying NOT NULL, "is_banned" boolean NOT NULL DEFAULT false, "is_deleted" boolean NOT NULL DEFAULT false, "role" "public"."users_role_enum" NOT NULL DEFAULT 'user', "phone_number" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."use_case_permissions_role_enum" AS ENUM('user', 'uniadmin', 'roomadmin', 'student', 'lecturer')`);
        await queryRunner.query(`CREATE TABLE "use_case_permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "role" "public"."use_case_permissions_role_enum" NOT NULL, "can_view" boolean NOT NULL DEFAULT true, "can_create" boolean NOT NULL DEFAULT false, "can_edit" boolean NOT NULL DEFAULT false, "can_delete" boolean NOT NULL DEFAULT false, "can_approve" boolean NOT NULL DEFAULT false, "usecase_id" uuid, CONSTRAINT "PK_942827107a940887f25c3d555e4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f2a0c2421f38e848a64e391a04" ON "use_case_permissions" ("role", "usecase_id") `);
        await queryRunner.query(`CREATE TYPE "public"."use_cases_priority_enum" AS ENUM('must_have', 'should_have', 'could_have', 'won''t_have')`);
        await queryRunner.query(`CREATE TABLE "use_cases" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "module" character varying NOT NULL, "uc_name" character varying NOT NULL, "description" character varying NOT NULL, "priority" "public"."use_cases_priority_enum" NOT NULL DEFAULT 'must_have', CONSTRAINT "PK_9051865dd5ae654c69eced58574" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_26083094aed4d2013541cb13fa" ON "use_cases" ("module") `);
        await queryRunner.query(`ALTER TABLE "class_members" ADD CONSTRAINT "FK_19bc9a374e6022841a1b66e6b06" FOREIGN KEY ("class") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_members" ADD CONSTRAINT "FK_4569afaf85946abfa3c9cbac1a6" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "checkbox_fields" ADD CONSTRAINT "FK_6b4236fbc851d1dfadc6060279f" FOREIGN KEY ("form") REFERENCES "forms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "checkbox_field_choices" ADD CONSTRAINT "FK_739f9f6f4d288f71eb7f0e088ef" FOREIGN KEY ("submission_checkbox") REFERENCES "submission_checkboxes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "submission_checkboxes" ADD CONSTRAINT "FK_2d43b289afe25e6542ffe01b757" FOREIGN KEY ("checkbox_field_id") REFERENCES "checkbox_fields"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "submission_checkboxes" ADD CONSTRAINT "FK_fb289e33564c2b3a7e454f9c5fd" FOREIGN KEY ("submission") REFERENCES "submissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD CONSTRAINT "FK_82318f9579f8f3df8480d46990f" FOREIGN KEY ("form_id") REFERENCES "forms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD CONSTRAINT "FK_e52c0f3546330ff0298c2dcecef" FOREIGN KEY ("user") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "submission_answers" ADD CONSTRAINT "FK_e353995ac74b8afd81d44ea89e0" FOREIGN KEY ("field") REFERENCES "fields"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "submission_answers" ADD CONSTRAINT "FK_e9497b4ebc4cc0810b379a712ad" FOREIGN KEY ("submission") REFERENCES "submissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fields" ADD CONSTRAINT "FK_f5f2c68138a8dabd583066aa8da" FOREIGN KEY ("form") REFERENCES "forms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forms" ADD CONSTRAINT "FK_6cb2e561e99b659d0e005325541" FOREIGN KEY ("milestone") REFERENCES "milestones"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forms" ADD CONSTRAINT "FK_9d51c393dea8ee5d2751b50038a" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "score_form_rows" ADD CONSTRAINT "FK_41f20b0e9d6ce2fbe8bf820b64e" FOREIGN KEY ("student") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "score_form_rows" ADD CONSTRAINT "FK_dd182580128c759796777e0f63a" FOREIGN KEY ("score_form") REFERENCES "score_forms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "score_form_cells" ADD CONSTRAINT "FK_d9414850baf1d84be086933459b" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "score_form_cells" ADD CONSTRAINT "FK_df888b49c295cf86cf996f000dc" FOREIGN KEY ("row") REFERENCES "score_form_rows"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "score_form_cells" ADD CONSTRAINT "FK_7df938140d81b7c4df7621ccf97" FOREIGN KEY ("column") REFERENCES "score_form_columns"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "score_form_columns" ADD CONSTRAINT "FK_f9ff4add6e75b532cefe9a69208" FOREIGN KEY ("score_form") REFERENCES "score_forms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "score_forms" ADD CONSTRAINT "FK_944bcea92e72236a2068810a99e" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "score_forms" ADD CONSTRAINT "FK_a2d5b0f39505b94e9abf729ed91" FOREIGN KEY ("milestone") REFERENCES "milestones"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "milestones" ADD CONSTRAINT "FK_efcffe415d887bdcd12593fa5b8" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "milestones" ADD CONSTRAINT "FK_a34419a251bc6cbed29ae1a89ed" FOREIGN KEY ("progress") REFERENCES "progresses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "progresses" ADD CONSTRAINT "FK_ac93063c66ee4068895da96ac65" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "progresses" ADD CONSTRAINT "FK_b6ff555471c0d266d5621b94eda" FOREIGN KEY ("class") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_0f5300b69d81de1ea6c9a12eda3" FOREIGN KEY ("class") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_19629e8eb1e6023c4c73e661c82" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classes" ADD CONSTRAINT "FK_b6a13513adb2003085d292f791e" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "use_case_permissions" ADD CONSTRAINT "FK_91617c2700022bd652614cb82e8" FOREIGN KEY ("usecase_id") REFERENCES "use_cases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "use_case_permissions" DROP CONSTRAINT "FK_91617c2700022bd652614cb82e8"`);
        await queryRunner.query(`ALTER TABLE "classes" DROP CONSTRAINT "FK_b6a13513adb2003085d292f791e"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_19629e8eb1e6023c4c73e661c82"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_0f5300b69d81de1ea6c9a12eda3"`);
        await queryRunner.query(`ALTER TABLE "progresses" DROP CONSTRAINT "FK_b6ff555471c0d266d5621b94eda"`);
        await queryRunner.query(`ALTER TABLE "progresses" DROP CONSTRAINT "FK_ac93063c66ee4068895da96ac65"`);
        await queryRunner.query(`ALTER TABLE "milestones" DROP CONSTRAINT "FK_a34419a251bc6cbed29ae1a89ed"`);
        await queryRunner.query(`ALTER TABLE "milestones" DROP CONSTRAINT "FK_efcffe415d887bdcd12593fa5b8"`);
        await queryRunner.query(`ALTER TABLE "score_forms" DROP CONSTRAINT "FK_a2d5b0f39505b94e9abf729ed91"`);
        await queryRunner.query(`ALTER TABLE "score_forms" DROP CONSTRAINT "FK_944bcea92e72236a2068810a99e"`);
        await queryRunner.query(`ALTER TABLE "score_form_columns" DROP CONSTRAINT "FK_f9ff4add6e75b532cefe9a69208"`);
        await queryRunner.query(`ALTER TABLE "score_form_cells" DROP CONSTRAINT "FK_7df938140d81b7c4df7621ccf97"`);
        await queryRunner.query(`ALTER TABLE "score_form_cells" DROP CONSTRAINT "FK_df888b49c295cf86cf996f000dc"`);
        await queryRunner.query(`ALTER TABLE "score_form_cells" DROP CONSTRAINT "FK_d9414850baf1d84be086933459b"`);
        await queryRunner.query(`ALTER TABLE "score_form_rows" DROP CONSTRAINT "FK_dd182580128c759796777e0f63a"`);
        await queryRunner.query(`ALTER TABLE "score_form_rows" DROP CONSTRAINT "FK_41f20b0e9d6ce2fbe8bf820b64e"`);
        await queryRunner.query(`ALTER TABLE "forms" DROP CONSTRAINT "FK_9d51c393dea8ee5d2751b50038a"`);
        await queryRunner.query(`ALTER TABLE "forms" DROP CONSTRAINT "FK_6cb2e561e99b659d0e005325541"`);
        await queryRunner.query(`ALTER TABLE "fields" DROP CONSTRAINT "FK_f5f2c68138a8dabd583066aa8da"`);
        await queryRunner.query(`ALTER TABLE "submission_answers" DROP CONSTRAINT "FK_e9497b4ebc4cc0810b379a712ad"`);
        await queryRunner.query(`ALTER TABLE "submission_answers" DROP CONSTRAINT "FK_e353995ac74b8afd81d44ea89e0"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP CONSTRAINT "FK_e52c0f3546330ff0298c2dcecef"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP CONSTRAINT "FK_82318f9579f8f3df8480d46990f"`);
        await queryRunner.query(`ALTER TABLE "submission_checkboxes" DROP CONSTRAINT "FK_fb289e33564c2b3a7e454f9c5fd"`);
        await queryRunner.query(`ALTER TABLE "submission_checkboxes" DROP CONSTRAINT "FK_2d43b289afe25e6542ffe01b757"`);
        await queryRunner.query(`ALTER TABLE "checkbox_field_choices" DROP CONSTRAINT "FK_739f9f6f4d288f71eb7f0e088ef"`);
        await queryRunner.query(`ALTER TABLE "checkbox_fields" DROP CONSTRAINT "FK_6b4236fbc851d1dfadc6060279f"`);
        await queryRunner.query(`ALTER TABLE "class_members" DROP CONSTRAINT "FK_4569afaf85946abfa3c9cbac1a6"`);
        await queryRunner.query(`ALTER TABLE "class_members" DROP CONSTRAINT "FK_19bc9a374e6022841a1b66e6b06"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_26083094aed4d2013541cb13fa"`);
        await queryRunner.query(`DROP TABLE "use_cases"`);
        await queryRunner.query(`DROP TYPE "public"."use_cases_priority_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f2a0c2421f38e848a64e391a04"`);
        await queryRunner.query(`DROP TABLE "use_case_permissions"`);
        await queryRunner.query(`DROP TYPE "public"."use_case_permissions_role_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "classes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b85731582ba550f9f38cb193a4"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "progresses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3981c3d8ecb4c98fd1feff697f"`);
        await queryRunner.query(`DROP TABLE "milestones"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bec6aec16056db33a4fefa4bac"`);
        await queryRunner.query(`DROP TABLE "score_forms"`);
        await queryRunner.query(`DROP TYPE "public"."score_forms_score_form_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f9ff4add6e75b532cefe9a6920"`);
        await queryRunner.query(`DROP TABLE "score_form_columns"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b4b4e45572d49b4656ee2cbff0"`);
        await queryRunner.query(`DROP TABLE "score_form_cells"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c3751f1bcb296748570b38595"`);
        await queryRunner.query(`DROP TABLE "score_form_rows"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a3b3a7866f18e227340c0e1c01"`);
        await queryRunner.query(`DROP TABLE "forms"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f5f2c68138a8dabd583066aa8d"`);
        await queryRunner.query(`DROP TABLE "fields"`);
        await queryRunner.query(`DROP TYPE "public"."fields_unit_enum"`);
        await queryRunner.query(`DROP TYPE "public"."fields_input_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."fields_label_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0c7afc9bb5f426d5020c7dea1c"`);
        await queryRunner.query(`DROP TABLE "submission_answers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4bebcd2af113fc32d00ed64d7e"`);
        await queryRunner.query(`DROP TABLE "submissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_03c60815fd5dcdc496e2a2c911"`);
        await queryRunner.query(`DROP TABLE "submission_checkboxes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_739f9f6f4d288f71eb7f0e088e"`);
        await queryRunner.query(`DROP TABLE "checkbox_field_choices"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6b4236fbc851d1dfadc6060279"`);
        await queryRunner.query(`DROP TABLE "checkbox_fields"`);
        await queryRunner.query(`DROP TYPE "public"."checkbox_fields_input_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c38b69071bb1cad72777d45502"`);
        await queryRunner.query(`DROP TABLE "class_members"`);
        await queryRunner.query(`DROP TYPE "public"."class_members_role_enum"`);
    }

}
