import { MigrationInterface, QueryRunner } from "typeorm";

export class InitDB1777277240682 implements MigrationInterface {
    name = 'InitDB1777277240682'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "public"."class_members_role_enum" AS ENUM('roomadmin', 'student', 'lecturer'); EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "class_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "role" "public"."class_members_role_enum" NOT NULL DEFAULT 'student', "roomadmin_approved" boolean NOT NULL DEFAULT false, "is_banned" boolean NOT NULL DEFAULT false, "is_deleted" boolean NOT NULL DEFAULT false, "is_committee_member" boolean NOT NULL DEFAULT false, "can_create_notifications" boolean NOT NULL DEFAULT false, "can_create_forms" boolean NOT NULL DEFAULT false, "can_create_score_forms" boolean NOT NULL DEFAULT false, "joined_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "class" uuid, "user_id" uuid, CONSTRAINT "PK_c06d2c3bc732509dcbbab8d5730" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_c38b69071bb1cad72777d45502" ON "class_members" ("class", "user_id") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "checkbox_field_choices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "index" integer NOT NULL, "body" character varying NOT NULL, "checkbox_field" uuid, CONSTRAINT "PK_69534eae5b5aaba2b70902948f8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "public"."checkbox_fields_input_type_enum" AS ENUM('string', 'number', 'file', 'checkbox'); EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "checkbox_fields" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "index" integer NOT NULL, "title" character varying NOT NULL, "description" character varying, "input_type" "public"."checkbox_fields_input_type_enum" NOT NULL DEFAULT 'checkbox', "choice_count" integer NOT NULL, "is_required" boolean NOT NULL DEFAULT false, "is_multiple" boolean NOT NULL DEFAULT false, "is_deleted" boolean NOT NULL DEFAULT false, "update_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "form" uuid, CONSTRAINT "PK_d5699c122fde6c00a2dc102889e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_6b4236fbc851d1dfadc6060279" ON "checkbox_fields" ("form") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "submission_checkboxes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "checkbox_field" uuid, "fieldChoicesId" uuid, "submission" uuid, CONSTRAINT "PK_2600970eab4f2d485873ad89a77" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_4c2a3a815fd83a20958e863a92" ON "submission_checkboxes" ("checkbox_field", "submission") `);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "public"."submissions_status_enum" AS ENUM('pending', 'receive', 'accept', 'reject'); EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "submissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."submissions_status_enum" NOT NULL DEFAULT 'pending', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "form_id" uuid, "user" uuid, CONSTRAINT "PK_10b3be95b8b2fb1e482e07d706b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_4bebcd2af113fc32d00ed64d7e" ON "submissions" ("user", "form_id") `);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "public"."submission_answers_input_type_enum" AS ENUM('string', 'number', 'file', 'checkbox'); EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "submission_answers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "body" character varying, "input_type" "public"."submission_answers_input_type_enum" NOT NULL DEFAULT 'string', "field" uuid, "submission" uuid, CONSTRAINT "PK_32d8f1ef26cf32a2e8ba2f1fc13" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_0c7afc9bb5f426d5020c7dea1c" ON "submission_answers" ("field", "submission") `);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "public"."fields_label_enum" AS ENUM('null', 'outline_file', 'report_file', 'final_thesis', 'supervisor_review_file', 'revision_file'); EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "public"."fields_input_type_enum" AS ENUM('string', 'number', 'file', 'checkbox'); EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "public"."fields_unit_enum" AS ENUM('file', 'unit', 'character'); EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "fields" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "index" integer NOT NULL, "label" "public"."fields_label_enum" NOT NULL DEFAULT 'null', "title" character varying NOT NULL, "description" character varying, "input_type" "public"."fields_input_type_enum" NOT NULL DEFAULT 'string', "is_required" boolean NOT NULL DEFAULT false, "unit" "public"."fields_unit_enum" NOT NULL, "max_attempts" integer NOT NULL DEFAULT '20', "min_attempts" integer NOT NULL DEFAULT '1', "is_deleted" boolean NOT NULL DEFAULT false, "update_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "form" uuid, CONSTRAINT "PK_ee7a215c6cd77a59e2cb3b59d41" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_f5f2c68138a8dabd583066aa8d" ON "fields" ("form") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "body" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "class" uuid, "created_by" uuid, "milestone" uuid, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_b85731582ba550f9f38cb193a4" ON "notifications" ("class", "created_by") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "forms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "is_join_form" boolean NOT NULL DEFAULT false, "label" character varying NOT NULL, "description" character varying, "field_count" integer NOT NULL, "is_auto_open" boolean NOT NULL DEFAULT false, "is_auto_close" boolean NOT NULL DEFAULT false, "is_deleted" boolean NOT NULL DEFAULT false, "is_stopped" boolean NOT NULL DEFAULT false, "open_at" TIMESTAMP WITH TIME ZONE, "close_at" TIMESTAMP WITH TIME ZONE, "update_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "milestone" uuid, "created_by" uuid, "class" uuid, CONSTRAINT "PK_ba062fd30b06814a60756f233da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_a3b3a7866f18e227340c0e1c01" ON "forms" ("label", "milestone", "created_by", "is_auto_open", "is_auto_close", "is_deleted", "is_stopped") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "score_form_rows" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "index" integer NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "student" uuid, "score_form" uuid, CONSTRAINT "PK_167e7f35eb59b73f48212913075" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_5c3751f1bcb296748570b38595" ON "score_form_rows" ("student", "score_form") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "score_form_cells" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "value" character varying, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" uuid, "score_form" uuid, "row" uuid, "column" uuid, CONSTRAINT "PK_a6c354a8b56e4ccb40a75a46ae6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_b4b4e45572d49b4656ee2cbff0" ON "score_form_cells" ("updated_by", "row", "column") `);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "public"."score_form_columns_allowed_role_enum" AS ENUM('roomadmin', 'lecturer', 'chairman', 'reviewer', 'member'); EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "public"."score_form_columns_column_type_enum" AS ENUM('normal', 'component', 'summary'); EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "public"."score_form_columns_column_label_enum" AS ENUM('last_name', 'first_name'); EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "score_form_columns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "label" character varying NOT NULL, "index" integer NOT NULL, "formula_content" character varying, "allowed_role" "public"."score_form_columns_allowed_role_enum", "column_type" "public"."score_form_columns_column_type_enum" NOT NULL DEFAULT 'normal', "column_label" "public"."score_form_columns_column_label_enum", "score_form" uuid, CONSTRAINT "PK_6c3b5eee0dafb23568868cffee1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_f9ff4add6e75b532cefe9a6920" ON "score_form_columns" ("score_form") `);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "public"."score_forms_score_form_type_enum" AS ENUM('supervisor_score', 'reviewer_score', 'committee_score', 'attendance_check', 'bonus_score', 'others'); EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "public"."score_forms_status_enum" AS ENUM('pending', 'receive', 'accept', 'reject'); EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "score_forms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "score_form_type" "public"."score_forms_score_form_type_enum" NOT NULL DEFAULT 'others', "status" "public"."score_forms_status_enum" NOT NULL DEFAULT 'pending', "label" character varying NOT NULL, "description" character varying, "field_count" integer NOT NULL, "is_auto_open" boolean NOT NULL DEFAULT false, "is_auto_close" boolean NOT NULL DEFAULT false, "is_deleted" boolean NOT NULL DEFAULT false, "is_stopped" boolean NOT NULL DEFAULT false, "open_at" TIMESTAMP WITH TIME ZONE, "close_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "update_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, "milestone" uuid, "class" uuid, CONSTRAINT "PK_886b88e54e4de99da664c91bed2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_bec6aec16056db33a4fefa4bac" ON "score_forms" ("label", "milestone", "created_by", "is_auto_open", "is_auto_close", "is_deleted", "is_stopped") `);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "public"."topics_thesis_type_enum" AS ENUM('thesis', 'capstone'); EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "public"."topics_status_enum" AS ENUM('draft', 'invited', 'supervisor_rejected', 'supervisor_accepted', 'outline_pending', 'outline_rejected', 'approved'); EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "topics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" character varying, "thesis_type" "public"."topics_thesis_type_enum" NOT NULL, "status" "public"."topics_status_enum" NOT NULL DEFAULT 'draft', "rejection_note" character varying, "outline_file_url" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "milestone_id" uuid, "student_id" uuid, "supervisor_id" uuid, CONSTRAINT "PK_e4aa99a3fa60ec3a37d1fc4e853" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_2dc8525642946e546f3e04cab5" ON "topics" ("milestone_id", "student_id") `);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "public"."committee_members_role_enum" AS ENUM('chairman', 'reviewer', 'member', 'secretary'); EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "committee_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "role" "public"."committee_members_role_enum" NOT NULL, "committee_id" uuid, "user_id" uuid, CONSTRAINT "PK_d674c70e45241dde1bd9d8fe21b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_af4b0c001ab0947686df0e8a8f" ON "committee_members" ("committee_id", "user_id") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "committees" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "class_id" uuid, "milestone_id" uuid, CONSTRAINT "PK_69acdd168edf3e61a2a0b4ed13b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_e9ac60ff341896640aaff4d7df" ON "committees" ("class_id") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "milestones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "index" integer NOT NULL, "label" character varying NOT NULL DEFAULT true, "description" character varying, "is_deleted" boolean NOT NULL DEFAULT false, "is_stopped" boolean NOT NULL DEFAULT false, "is_registration_milestone" boolean NOT NULL DEFAULT false, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, "progress" uuid, CONSTRAINT "PK_0bdbfe399c777a6a8520ff902d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_3981c3d8ecb4c98fd1feff697f" ON "milestones" ("progress", "label", "created_by", "is_deleted", "is_stopped") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "progresses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "label" character varying, "description" character varying, "is_deleted" boolean NOT NULL DEFAULT false, "is_submitted" boolean NOT NULL DEFAULT false, "is_banned" boolean NOT NULL DEFAULT false, "created_approval" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, "class" uuid, CONSTRAINT "REL_b6ff555471c0d266d5621b94ed" UNIQUE ("class"), CONSTRAINT "PK_8bd707ae89e9482ebf23658011e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "classes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "join_code" character varying, "label" character varying NOT NULL DEFAULT 'Lớp học mới', "description" character varying, "subject" character varying NOT NULL, "created_approval" boolean NOT NULL DEFAULT false, "required_approval" boolean NOT NULL DEFAULT false, "required_join_form" boolean NOT NULL DEFAULT false, "is_deleted" boolean NOT NULL DEFAULT false, "is_banned" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, CONSTRAINT "PK_e207aa15404e9b2ce35910f9f7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "public"."users_role_enum" AS ENUM('user', 'uniadmin'); EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "supabase_id" character varying NOT NULL, "full_name" character varying NOT NULL, "email" character varying NOT NULL, "is_banned" boolean NOT NULL DEFAULT false, "is_deleted" boolean NOT NULL DEFAULT false, "role" "public"."users_role_enum" NOT NULL DEFAULT 'user', "phone_number" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "notification_forms" ("notification_id" uuid NOT NULL, "form_id" uuid NOT NULL, CONSTRAINT "PK_11dd1a478b31104b1284f8a65b6" PRIMARY KEY ("notification_id", "form_id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_fc9a29c923c422be15ac869b60" ON "notification_forms" ("notification_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_f011e7c93890da6a4572f9f839" ON "notification_forms" ("form_id") `);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "class_members" ADD CONSTRAINT "FK_19bc9a374e6022841a1b66e6b06" FOREIGN KEY ("class") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "class_members" ADD CONSTRAINT "FK_4569afaf85946abfa3c9cbac1a6" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "checkbox_field_choices" ADD CONSTRAINT "FK_50dabe2d45dbee75da2ddf8c68c" FOREIGN KEY ("checkbox_field") REFERENCES "checkbox_fields"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "checkbox_fields" ADD CONSTRAINT "FK_6b4236fbc851d1dfadc6060279f" FOREIGN KEY ("form") REFERENCES "forms"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "submission_checkboxes" ADD CONSTRAINT "FK_bcbf5c36305327a549d3cc9d489" FOREIGN KEY ("checkbox_field") REFERENCES "checkbox_fields"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "submission_checkboxes" ADD CONSTRAINT "FK_58ee14800951f128a5afbcd9e82" FOREIGN KEY ("fieldChoicesId") REFERENCES "checkbox_field_choices"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "submission_checkboxes" ADD CONSTRAINT "FK_fb289e33564c2b3a7e454f9c5fd" FOREIGN KEY ("submission") REFERENCES "submissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "submissions" ADD CONSTRAINT "FK_82318f9579f8f3df8480d46990f" FOREIGN KEY ("form_id") REFERENCES "forms"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "submissions" ADD CONSTRAINT "FK_e52c0f3546330ff0298c2dcecef" FOREIGN KEY ("user") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "submission_answers" ADD CONSTRAINT "FK_e353995ac74b8afd81d44ea89e0" FOREIGN KEY ("field") REFERENCES "fields"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "submission_answers" ADD CONSTRAINT "FK_e9497b4ebc4cc0810b379a712ad" FOREIGN KEY ("submission") REFERENCES "submissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "fields" ADD CONSTRAINT "FK_f5f2c68138a8dabd583066aa8da" FOREIGN KEY ("form") REFERENCES "forms"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "notifications" ADD CONSTRAINT "FK_0f5300b69d81de1ea6c9a12eda3" FOREIGN KEY ("class") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "notifications" ADD CONSTRAINT "FK_19629e8eb1e6023c4c73e661c82" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "notifications" ADD CONSTRAINT "FK_c832e65200c7ae7567832b05472" FOREIGN KEY ("milestone") REFERENCES "milestones"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "forms" ADD CONSTRAINT "FK_6cb2e561e99b659d0e005325541" FOREIGN KEY ("milestone") REFERENCES "milestones"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "forms" ADD CONSTRAINT "FK_9d51c393dea8ee5d2751b50038a" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "forms" ADD CONSTRAINT "FK_2c6d9d9d7e2ef39e207a24f707b" FOREIGN KEY ("class") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "score_form_rows" ADD CONSTRAINT "FK_41f20b0e9d6ce2fbe8bf820b64e" FOREIGN KEY ("student") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "score_form_rows" ADD CONSTRAINT "FK_dd182580128c759796777e0f63a" FOREIGN KEY ("score_form") REFERENCES "score_forms"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "score_form_cells" ADD CONSTRAINT "FK_d9414850baf1d84be086933459b" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "score_form_cells" ADD CONSTRAINT "FK_0afc9c7b97e1d410eadf702bde7" FOREIGN KEY ("score_form") REFERENCES "score_forms"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "score_form_cells" ADD CONSTRAINT "FK_df888b49c295cf86cf996f000dc" FOREIGN KEY ("row") REFERENCES "score_form_rows"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "score_form_cells" ADD CONSTRAINT "FK_7df938140d81b7c4df7621ccf97" FOREIGN KEY ("column") REFERENCES "score_form_columns"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "score_form_columns" ADD CONSTRAINT "FK_f9ff4add6e75b532cefe9a69208" FOREIGN KEY ("score_form") REFERENCES "score_forms"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "score_forms" ADD CONSTRAINT "FK_944bcea92e72236a2068810a99e" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "score_forms" ADD CONSTRAINT "FK_a2d5b0f39505b94e9abf729ed91" FOREIGN KEY ("milestone") REFERENCES "milestones"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "score_forms" ADD CONSTRAINT "FK_fcbd1d8b1cb4297ff9522265356" FOREIGN KEY ("class") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "topics" ADD CONSTRAINT "FK_f16d6e4733cdf1ab59220b6dbf8" FOREIGN KEY ("milestone_id") REFERENCES "milestones"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "topics" ADD CONSTRAINT "FK_f2c7d2f6fd9f8a723aaafaf61e4" FOREIGN KEY ("student_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "topics" ADD CONSTRAINT "FK_c75cf0ad67f1b8644849c7e2dd6" FOREIGN KEY ("supervisor_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "committee_members" ADD CONSTRAINT "FK_7410db6ee097228a8f3b2035aa4" FOREIGN KEY ("committee_id") REFERENCES "committees"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "committee_members" ADD CONSTRAINT "FK_66d23529f51e9060e7ab7b337e6" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "committees" ADD CONSTRAINT "FK_e9ac60ff341896640aaff4d7df1" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "committees" ADD CONSTRAINT "FK_8fa2f20c1cb8e8304fc60e431d6" FOREIGN KEY ("milestone_id") REFERENCES "milestones"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "milestones" ADD CONSTRAINT "FK_efcffe415d887bdcd12593fa5b8" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "milestones" ADD CONSTRAINT "FK_a34419a251bc6cbed29ae1a89ed" FOREIGN KEY ("progress") REFERENCES "progresses"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "progresses" ADD CONSTRAINT "FK_ac93063c66ee4068895da96ac65" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "progresses" ADD CONSTRAINT "FK_b6ff555471c0d266d5621b94eda" FOREIGN KEY ("class") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "classes" ADD CONSTRAINT "FK_b6a13513adb2003085d292f791e" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "notification_forms" ADD CONSTRAINT "FK_fc9a29c923c422be15ac869b60e" FOREIGN KEY ("notification_id") REFERENCES "notifications"("id") ON DELETE CASCADE ON UPDATE CASCADE; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "notification_forms" ADD CONSTRAINT "FK_f011e7c93890da6a4572f9f8395" FOREIGN KEY ("form_id") REFERENCES "forms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; END $$;`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "notification_forms" DROP CONSTRAINT "FK_f011e7c93890da6a4572f9f8395"`);
        await queryRunner.query(`ALTER TABLE "notification_forms" DROP CONSTRAINT "FK_fc9a29c923c422be15ac869b60e"`);
        await queryRunner.query(`ALTER TABLE "classes" DROP CONSTRAINT "FK_b6a13513adb2003085d292f791e"`);
        await queryRunner.query(`ALTER TABLE "progresses" DROP CONSTRAINT "FK_b6ff555471c0d266d5621b94eda"`);
        await queryRunner.query(`ALTER TABLE "progresses" DROP CONSTRAINT "FK_ac93063c66ee4068895da96ac65"`);
        await queryRunner.query(`ALTER TABLE "milestones" DROP CONSTRAINT "FK_a34419a251bc6cbed29ae1a89ed"`);
        await queryRunner.query(`ALTER TABLE "milestones" DROP CONSTRAINT "FK_efcffe415d887bdcd12593fa5b8"`);
        await queryRunner.query(`ALTER TABLE "committees" DROP CONSTRAINT "FK_8fa2f20c1cb8e8304fc60e431d6"`);
        await queryRunner.query(`ALTER TABLE "committees" DROP CONSTRAINT "FK_e9ac60ff341896640aaff4d7df1"`);
        await queryRunner.query(`ALTER TABLE "committee_members" DROP CONSTRAINT "FK_66d23529f51e9060e7ab7b337e6"`);
        await queryRunner.query(`ALTER TABLE "committee_members" DROP CONSTRAINT "FK_7410db6ee097228a8f3b2035aa4"`);
        await queryRunner.query(`ALTER TABLE "topics" DROP CONSTRAINT "FK_c75cf0ad67f1b8644849c7e2dd6"`);
        await queryRunner.query(`ALTER TABLE "topics" DROP CONSTRAINT "FK_f2c7d2f6fd9f8a723aaafaf61e4"`);
        await queryRunner.query(`ALTER TABLE "topics" DROP CONSTRAINT "FK_f16d6e4733cdf1ab59220b6dbf8"`);
        await queryRunner.query(`ALTER TABLE "score_forms" DROP CONSTRAINT "FK_fcbd1d8b1cb4297ff9522265356"`);
        await queryRunner.query(`ALTER TABLE "score_forms" DROP CONSTRAINT "FK_a2d5b0f39505b94e9abf729ed91"`);
        await queryRunner.query(`ALTER TABLE "score_forms" DROP CONSTRAINT "FK_944bcea92e72236a2068810a99e"`);
        await queryRunner.query(`ALTER TABLE "score_form_columns" DROP CONSTRAINT "FK_f9ff4add6e75b532cefe9a69208"`);
        await queryRunner.query(`ALTER TABLE "score_form_cells" DROP CONSTRAINT "FK_7df938140d81b7c4df7621ccf97"`);
        await queryRunner.query(`ALTER TABLE "score_form_cells" DROP CONSTRAINT "FK_df888b49c295cf86cf996f000dc"`);
        await queryRunner.query(`ALTER TABLE "score_form_cells" DROP CONSTRAINT "FK_0afc9c7b97e1d410eadf702bde7"`);
        await queryRunner.query(`ALTER TABLE "score_form_cells" DROP CONSTRAINT "FK_d9414850baf1d84be086933459b"`);
        await queryRunner.query(`ALTER TABLE "score_form_rows" DROP CONSTRAINT "FK_dd182580128c759796777e0f63a"`);
        await queryRunner.query(`ALTER TABLE "score_form_rows" DROP CONSTRAINT "FK_41f20b0e9d6ce2fbe8bf820b64e"`);
        await queryRunner.query(`ALTER TABLE "forms" DROP CONSTRAINT "FK_2c6d9d9d7e2ef39e207a24f707b"`);
        await queryRunner.query(`ALTER TABLE "forms" DROP CONSTRAINT "FK_9d51c393dea8ee5d2751b50038a"`);
        await queryRunner.query(`ALTER TABLE "forms" DROP CONSTRAINT "FK_6cb2e561e99b659d0e005325541"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_c832e65200c7ae7567832b05472"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_19629e8eb1e6023c4c73e661c82"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_0f5300b69d81de1ea6c9a12eda3"`);
        await queryRunner.query(`ALTER TABLE "fields" DROP CONSTRAINT "FK_f5f2c68138a8dabd583066aa8da"`);
        await queryRunner.query(`ALTER TABLE "submission_answers" DROP CONSTRAINT "FK_e9497b4ebc4cc0810b379a712ad"`);
        await queryRunner.query(`ALTER TABLE "submission_answers" DROP CONSTRAINT "FK_e353995ac74b8afd81d44ea89e0"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP CONSTRAINT "FK_e52c0f3546330ff0298c2dcecef"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP CONSTRAINT "FK_82318f9579f8f3df8480d46990f"`);
        await queryRunner.query(`ALTER TABLE "submission_checkboxes" DROP CONSTRAINT "FK_fb289e33564c2b3a7e454f9c5fd"`);
        await queryRunner.query(`ALTER TABLE "submission_checkboxes" DROP CONSTRAINT "FK_58ee14800951f128a5afbcd9e82"`);
        await queryRunner.query(`ALTER TABLE "submission_checkboxes" DROP CONSTRAINT "FK_bcbf5c36305327a549d3cc9d489"`);
        await queryRunner.query(`ALTER TABLE "checkbox_fields" DROP CONSTRAINT "FK_6b4236fbc851d1dfadc6060279f"`);
        await queryRunner.query(`ALTER TABLE "checkbox_field_choices" DROP CONSTRAINT "FK_50dabe2d45dbee75da2ddf8c68c"`);
        await queryRunner.query(`ALTER TABLE "class_members" DROP CONSTRAINT "FK_4569afaf85946abfa3c9cbac1a6"`);
        await queryRunner.query(`ALTER TABLE "class_members" DROP CONSTRAINT "FK_19bc9a374e6022841a1b66e6b06"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f011e7c93890da6a4572f9f839"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fc9a29c923c422be15ac869b60"`);
        await queryRunner.query(`DROP TABLE "notification_forms"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "classes"`);
        await queryRunner.query(`DROP TABLE "progresses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3981c3d8ecb4c98fd1feff697f"`);
        await queryRunner.query(`DROP TABLE "milestones"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9ac60ff341896640aaff4d7df"`);
        await queryRunner.query(`DROP TABLE "committees"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af4b0c001ab0947686df0e8a8f"`);
        await queryRunner.query(`DROP TABLE "committee_members"`);
        await queryRunner.query(`DROP TYPE "public"."committee_members_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2dc8525642946e546f3e04cab5"`);
        await queryRunner.query(`DROP TABLE "topics"`);
        await queryRunner.query(`DROP TYPE "public"."topics_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."topics_thesis_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bec6aec16056db33a4fefa4bac"`);
        await queryRunner.query(`DROP TABLE "score_forms"`);
        await queryRunner.query(`DROP TYPE "public"."score_forms_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."score_forms_score_form_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f9ff4add6e75b532cefe9a6920"`);
        await queryRunner.query(`DROP TABLE "score_form_columns"`);
        await queryRunner.query(`DROP TYPE "public"."score_form_columns_column_label_enum"`);
        await queryRunner.query(`DROP TYPE "public"."score_form_columns_column_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."score_form_columns_allowed_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b4b4e45572d49b4656ee2cbff0"`);
        await queryRunner.query(`DROP TABLE "score_form_cells"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c3751f1bcb296748570b38595"`);
        await queryRunner.query(`DROP TABLE "score_form_rows"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a3b3a7866f18e227340c0e1c01"`);
        await queryRunner.query(`DROP TABLE "forms"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b85731582ba550f9f38cb193a4"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f5f2c68138a8dabd583066aa8d"`);
        await queryRunner.query(`DROP TABLE "fields"`);
        await queryRunner.query(`DROP TYPE "public"."fields_unit_enum"`);
        await queryRunner.query(`DROP TYPE "public"."fields_input_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."fields_label_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0c7afc9bb5f426d5020c7dea1c"`);
        await queryRunner.query(`DROP TABLE "submission_answers"`);
        await queryRunner.query(`DROP TYPE "public"."submission_answers_input_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4bebcd2af113fc32d00ed64d7e"`);
        await queryRunner.query(`DROP TABLE "submissions"`);
        await queryRunner.query(`DROP TYPE "public"."submissions_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c2a3a815fd83a20958e863a92"`);
        await queryRunner.query(`DROP TABLE "submission_checkboxes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6b4236fbc851d1dfadc6060279"`);
        await queryRunner.query(`DROP TABLE "checkbox_fields"`);
        await queryRunner.query(`DROP TYPE "public"."checkbox_fields_input_type_enum"`);
        await queryRunner.query(`DROP TABLE "checkbox_field_choices"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c38b69071bb1cad72777d45502"`);
        await queryRunner.query(`DROP TABLE "class_members"`);
        await queryRunner.query(`DROP TYPE "public"."class_members_role_enum"`);
    }

}
